name: CI - Build LSP Server with Cap'n Proto

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build_ubuntu:
    name: Build on Ubuntu (Custom Container)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/trickstar0301/capnp-prebuilt-ubuntu:1.1.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B build .
      - name: Build Project
        run: cmake --build build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capnp-ls-ubuntu
          path: build/capnp-ls

  build_macos:
    name: Build on macOS (Native Runner)
    runs-on: macos-latest
    env:
      CMAKE_LIBRARY_PATH: /opt/homebrew/lib
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Cap'n Proto (macOS)
        run: |
          set -e
          brew update
          brew install cmake
          brew install capnp
          brew link capnp --force

      - name: Configure CMake
        run: cmake -B build .
      - name: Build Project
        run: cmake --build build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capnp-ls-macos
          path: build/capnp-ls
