name: CI - Build LSP Server with Cap'n Proto

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build_ubuntu:
    name: Build on Ubuntu (Custom Container)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/trickstar0301/capnp-prebuilt-ubuntu:1.1.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B build .
      - name: Build Project
        run: cmake --build build
      - name: Rename Binary for Linux x86_64
        run: mv build/capnp-ls build/capnp-ls-linux-x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capnp-ls-linux-x86_64
          path: build/capnp-ls-linux-x86_64

  build_macos:
    name: Build on macOS (Apple Silicon - ARM64)
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Cap'n Proto (macOS)
        run: |
          set -e
          brew update
          brew install cmake capnp
          brew link capnp --force

      - name: Configure CMake
        run: cmake -B build .
      - name: Build Project
        run: cmake --build build
      - name: Rename Binary for macOS ARM64
        run: mv build/capnp-ls build/capnp-ls-macos-arm64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capnp-ls-macos-arm64
          path: build/capnp-ls-macos-arm64

  release:
    name: Create GitHub Release
    needs: [build_ubuntu, build_macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Linux x86_64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: capnp-ls-linux-x86_64
          path: artifacts

      - name: Download macOS ARM64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: capnp-ls-macos-arm64
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/capnp-ls-linux-x86_64
            artifacts/capnp-ls-macos-arm64
          draft: false
          prerelease: false
